---
id: 20231008120442
---
= latex: fonts terminology
:showtitle:
:toc:
:toc-title:

here i will try to describe some confusing terms i've used while setting up my
latex document:

* font sizes
* font styles
* font families
* font typefaces

## font sizes

in latex font size is declared by using special commands:

* `\small`
* `\large`
* etc.

check out ref guide <https://en.wikibooks.org/wiki/LaTeX/Fonts#Sizing_text> for a
complete list

i also want to note that these commands are **relative to the size set in
document's preamble**

## font styles

styles in latex are _bold_, _italics_, _underlined_, etc.

check out ref guide <https://en.wikibooks.org/wiki/LaTeX/Fonts#Font_styles>
for a complete list

## font families

a font family, or typeface, is a collection of characters that belong to one of
the following groups:

* serif
* sans-serif
* monospaced

for example, (1) times new roman is considered a serif font,
(2) arial - sans-serif, and (3) courier - monospaced.

check out ref guide
https://en.wikibooks.org/wiki/LaTeX/Fonts#Font_families for a complete list

## workflow

to stay consistent in configuring font settings i prefer the following
workflow order:

family -> style -> size

i'll explain what tex commands i use in another note later. see note #62.
