---
id: 20240906033707
---
= math: calculus
:showtitle:

there's a very good explanation on reddit by u/Dr0110111001101111
https://www.reddit.com/user/Dr0110111001101111/ about stewart's calculus:
early transcendentals

> Early Transcendentals is the way to go. This is the book that made James
> Stewart a very wealthy guy.
>
> Prior to Stewart writing that book, virtually every calculus book used a
> sequence that is now known as "late transcendentals". They didn't have a term
> for it back then, because they didn't need one. It was the only way to go.
> The most fundamental difference is the way certain topics are defined, which
> results in a slightly different order of topics.
>
Calculus can broadly be divided into three topics: limits, derivatives,
> and integrals. You can throw series in there as a fourth if you'd like.
>
> Nearly every book starts with limits, then introduces derivatives. But here
> is where they split. The "late transcendentals" approach doesn't teach you
> how to do derivatives for every kind of function right away. They do most
> of them, but then need to move on to integrals before they can finish
> derivatives. This is because "late transcendentals" books define the
> log function as the integral of another function. Now that it's defined,
> they can circle back to showing you a derivative for that function.
>
> Stewart came up with a clever way to deal with logs without defining it as an
> integral. He just uses the same definitions for functions that you learned
> in your algebra classes. This allowed him to give a complete section
> on derivatives for all the main parents functions before moving on to
> integration. It tidies up the table of contents quite a bit.
>
> After this, virtually every new calculus book took that approach. There are
> some old fashioned folks that still turn their noses up at it, but I think
> it's just as rigorous as the old way in the context of a first-year
> calculus book.

the comment thread continues w/ another one from u/call-it-karma-
https://www.reddit.com/user/call-it-karma-/

> Chapters 1-5 are typically calc 1 +
> Chapters 6-11 are typically calc 2 +
> Chapters 12-16 are typically calc 3 +
> Chapter 17 may be taught in calc 3 but covers topics that are more
> appropriate for a Diff EQ class.

here's the link to this page on reddit
https://www.reddit.com/r/learnmath/comments/s138kx/which_stewart_calculus_textbook/
